{% set version = "0.2.0" %}

package:
  name: mi-cpptest
  version: {{ version }}

source:
  url: https://github.com/metno/mi-cpptest/archive/v{{ version }}.tar.gz
  sha256: 96f3e0e95a5634b3db773f4ca2e2d8b248647518b5eca57a529b233992c1105e
  folder: source

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make         # [not win]
    - ninja        # [win]

test:
  commands:
    - test -f $PREFIX/include/mi_cpptest.h  # [unix]

about:
  home: https://github.com/metno/mi-cpptest
  license: GPL-2.0-or-later
  license_file: source/LICENSE.txt
  summary: MET Norway C++ unit test library

extra:
  recipe-maintainers:
    - alexander-buerger-met-no
    - audunc
    - heikoklein
